version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-north-1:422653419447:task-definition/myapp-task-production:2"
        LoadBalancerInfo:
          ContainerName: myapp
          ContainerPort: 3000

